/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  BrowseRequest,
  BrowseResponse,
  IndexBootstrapRequest,
  IndexBootstrapResponse,
  PostApiV1EntityCreate201,
  PostApiV1EntityCreateBody,
  PostApiV1FileCategoryCreate201,
  PostApiV1FileCategoryCreateBody,
  PostApiV1FileExtensionCreate201,
  PostApiV1FileExtensionCreateBody,
  PostApiV1FileTusIntent201,
  PostApiV1FileTusIntentBody,
  PostApiV1FileTusSeal200,
  PostApiV1FileTusSealBody,
  PostApiV1ItemCreate201,
  PostApiV1ItemCreateBody,
  PostApiV1UserCreate201,
  PostApiV1UserCreateBody,
  ResolveItemFilesRequest,
  ResolveItemFilesResponse,
  SearchRequest,
  SearchResponse
} from '.././model';

import { customInstance } from '.././mutator';






@Injectable({ providedIn: 'root' })
export class DefaultService {
  private readonly http = inject(HttpClient);
 getApiV1TraceId<TData = string>(
    id: string,
 ) {
      return customInstance<TData>(
      {url: `/api/v1/trace/${id}`, method: 'GET'
    },
      this.http,
      );
    }
  /**
 * 建立一個新實體，並初始化相關資料。
 * @summary 建立新實體
 */
 postApiV1EntityCreate<TData = PostApiV1EntityCreate201>(
    postApiV1EntityCreateBody: PostApiV1EntityCreateBody,
 ) {
      return customInstance<TData>(
      {url: `/api/v1/entity/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1EntityCreateBody
    },
      this.http,
      );
    }
  /**
 * 在 Tus 正式開始前先建立檔案意圖與暫存狀態。
 * @summary 建立 Tus 上傳意圖
 */
 postApiV1FileTusIntent<TData = PostApiV1FileTusIntent201>(
    postApiV1FileTusIntentBody: PostApiV1FileTusIntentBody,
 ) {
      return customInstance<TData>(
      {url: `/api/v1/file/tus-intent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1FileTusIntentBody
    },
      this.http,
      );
    }
  /**
 * 上傳完成後進行最終確認，更新檔案狀態並觸發後續同步。
 * @summary Tus 上傳最終確認
 */
 postApiV1FileTusSeal<TData = PostApiV1FileTusSeal200>(
    postApiV1FileTusSealBody: PostApiV1FileTusSealBody,
 ) {
      return customInstance<TData>(
      {url: `/api/v1/file/tus-seal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1FileTusSealBody
    },
      this.http,
      );
    }
  /**
 * 新增一筆檔案分類設定（FileCategory）。
 * @summary 新增檔案分類
 */
 postApiV1FileCategoryCreate<TData = PostApiV1FileCategoryCreate201>(
    postApiV1FileCategoryCreateBody: PostApiV1FileCategoryCreateBody,
 ) {
      return customInstance<TData>(
      {url: `/api/v1/file/category/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1FileCategoryCreateBody
    },
      this.http,
      );
    }
  /**
 * 新增一筆副檔名設定（FileExtension），並關聯至指定的分類。
 * @summary 新增副檔名
 */
 postApiV1FileExtensionCreate<TData = PostApiV1FileExtensionCreate201>(
    postApiV1FileExtensionCreateBody: PostApiV1FileExtensionCreateBody,
 ) {
      return customInstance<TData>(
      {url: `/api/v1/file/extension/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1FileExtensionCreateBody
    },
      this.http,
      );
    }
  /**
 * 建立一個新項目，並初始化相關資料。
 * @summary 建立新項目
 */
 postApiV1ItemCreate<TData = PostApiV1ItemCreate201>(
    postApiV1ItemCreateBody: PostApiV1ItemCreateBody,
 ) {
      return customInstance<TData>(
      {url: `/api/v1/item/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1ItemCreateBody
    },
      this.http,
      );
    }
  /**
 * 前端先拿全量索引，後續只透過 SSE 接收增量更新。
 * @summary 建立索引快照
 */
 postApiV1IndexBootstrap<TData = IndexBootstrapResponse>(
    indexBootstrapRequest: IndexBootstrapRequest,
 ) {
      return customInstance<TData>(
      {url: `/api/v1/index/bootstrap`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: indexBootstrapRequest
    },
      this.http,
      );
    }
  /**
 * 透過 MeiliSearch 搜尋項目，支援過濾語法與分頁
 * @summary 全文搜尋 Items
 */
 postApiV1SearchItems<TData = SearchResponse>(
    searchRequest: SearchRequest,
 ) {
      return customInstance<TData>(
      {url: `/api/v1/search/items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: searchRequest
    },
      this.http,
      );
    }
  /**
 * 回傳指定 Item 下 CONTAINS 關聯的檔案。不帶 itemId 時回傳頂層 Item 清單。
 * @summary 瀏覽 Item 內容
 */
 postApiV1ExplorerBrowse<TData = BrowseResponse>(
    browseRequest: BrowseRequest,
 ) {
      return customInstance<TData>(
      {url: `/api/v1/explorer/browse`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: browseRequest
    },
      this.http,
      );
    }
  /**
 * 用於瀏覽卡片懶加載，將 itemId 陣列轉換為 fileId 與 coverUrl。
 * @summary 批次解析 itemId 對應 fileId
 */
 postApiV1ExplorerResolveFiles<TData = ResolveItemFilesResponse>(
    resolveItemFilesRequest: ResolveItemFilesRequest,
 ) {
      return customInstance<TData>(
      {url: `/api/v1/explorer/resolve-files`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resolveItemFilesRequest
    },
      this.http,
      );
    }
  /**
 * 以 fileId 從磁碟讀取原始檔案，回傳 binary content 與正確的 Content-Type。圖片類型可直接作為 <img src="..."> 使用。
 * @summary 讀取檔案原始內容
 */
 getApiV1FilesFileIdServe<TData = Blob>(
    
 ) {
      return customInstance<TData>(
      {url: `/api/v1/files/:fileId/serve`, method: 'GET',
        responseType: 'blob'
    },
      this.http,
      );
    }
  /**
 * 建立一個新使用者，並初始化相關資料。
 * @summary 建立新使用者
 */
 postApiV1UserCreate<TData = PostApiV1UserCreate201>(
    postApiV1UserCreateBody: PostApiV1UserCreateBody,
 ) {
      return customInstance<TData>(
      {url: `/api/v1/user/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1UserCreateBody
    },
      this.http,
      );
    }
  };

