/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
export interface IndexBootstrapResponse {
  success: boolean;
  /** 快照版本，可用於除錯與追蹤 */
  version: number;
  /** 索引中可用的 item id 清單；item 對應 file 資訊已由伺服器預熱至共享快取 */
  itemIds: string[];
}

export interface IndexBootstrapRequest {
  /** SSE trace id，前端用同一個 id 接收增量事件 */
  notifyUploadId: string;
}

export type SearchHitMetadata = {[key: string]: unknown | null};

export interface SearchHit {
  id: string;
  title: string;
  type: string;
  status: string;
  metadata: SearchHitMetadata;
  publishedTime: number | null;
  createdTime: number;
  modifiedTime: number;
}

export interface SearchResponse {
  hits: SearchHit[];
  /** 估計總筆數 */
  total: number;
  limit: number;
  offset: number;
}

export interface SearchRequest {
  /** 搜尋關鍵字，空字串回傳所有結果 */
  q?: string;
  /** MeiliSearch 過濾語法，例如 type = "WORK" */
  filter?: string;
  /**
   * 每頁筆數
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * 分頁位移
   * @minimum 0
   */
  offset?: number;
}

/**
 * 項目類型
 */
export type IndexEntryType = typeof IndexEntryType[keyof typeof IndexEntryType];


export const IndexEntryType = {
  WORK: 'WORK',
  SERIES: 'SERIES',
  COLLECTION: 'COLLECTION',
  FILE_CONTAINER: 'FILE_CONTAINER',
} as const;

/**
 * 擴充屬性
 */
export type IndexEntryMetadata = {[key: string]: unknown | null};

export interface IndexEntry {
  /** 項目 UUID */
  id: string;
  /** 項目類型 */
  type: IndexEntryType;
  /** 項目名稱 */
  name: string;
  /** 是否已刪除 */
  is_deleted?: boolean;
  /** 是否隱藏 */
  is_hidden?: boolean;
  /** 是否為自動產生 */
  is_generated?: boolean;
  /** 是否置頂 */
  is_pinned?: boolean;
  /** 建立時間 (ms) */
  created_at: number;
  /** 更新時間 (ms) */
  updated_at: number;
  /** 發布時間 (ms) */
  published_at?: number;
  /** 總頁數 */
  pages?: number;
  /** 內容數量 */
  count?: number;
  /** 排序權重 */
  position?: number;
  /** 標籤 ID 列表 */
  tags?: string[];
  /** 擴充屬性 */
  metadata?: IndexEntryMetadata;
}

export interface Breadcrumb {
  id: string;
  name: string;
}

export interface BrowseResponse {
  entries: IndexEntry[];
  /** 導覽路徑 (根 → 當前)，根目錄時為空陣列 */
  breadcrumbs: Breadcrumb[];
  hasMore: boolean;
  nextCursor: string | null;
}

/**
 * NORMAL = 正常內容，DELETED = 已刪除
 */
export type BrowseRequestViewMode = typeof BrowseRequestViewMode[keyof typeof BrowseRequestViewMode];


export const BrowseRequestViewMode = {
  NORMAL: 'NORMAL',
  DELETED: 'DELETED',
} as const;

export interface BrowseRequest {
  /** 瀏覽指定 Item 的內容，省略則回傳頂層清單 */
  itemId?: string;
  /** NORMAL = 正常內容，DELETED = 已刪除 */
  viewMode?: BrowseRequestViewMode;
  /** 游標分頁：上一頁最後一筆的 id */
  lastId?: string;
  /**
   * 每頁筆數
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
}

export interface ItemFileResolution {
  itemId: string;
  fileId: string | null;
  coverUrl: string | null;
}

export interface ResolveItemFilesResponse {
  mappings: ItemFileResolution[];
}

export interface ResolveItemFilesRequest {
  /**
   * 需要解析的 itemId 清單
   * @minItems 1
   * @maxItems 200
   */
  itemIds: string[];
}

/**
 * 單一或批次建立實體的輸入資料
 */
export type PostApiV1EntityCreateBody = ({
  /**
   * 實體名稱，至少 1 個字元
   * @minLength 1
   */
  name: string;
  /** 實體描述，用於補充說明此實體用途 */
  description?: string;
  /** 自訂鍵值對 metadata，可存放額外設定或標記 */
  metadata?: {[key: string]: unknown | null};
})[] | {
  /**
   * 實體名稱，至少 1 個字元
   * @minLength 1
   */
  name: string;
  /** 實體描述，用於補充說明此實體用途 */
  description?: string;
  /** 自訂鍵值對 metadata，可存放額外設定或標記 */
  metadata?: {[key: string]: unknown | null};
};

export type PostApiV1EntityCreate201 = {
  success: boolean;
  traceId: string;
};

/**
 * 支援單筆 file 或批次 files 的 Tus 意圖輸入
 */
export type PostApiV1FileTusIntentBody = {
  /** 唯一的工作流程追蹤 ID，用於關聯整個檔案上傳流程中的各個階段 */
  notifyUploadId: string;
  /** 單一待建立檔案資料 */
  file: {
  /** 檔名 */
  name: string;
  /**
   * 檔案大小 (bytes)
   * @pattern ^d+$
   */
  size: string;
  /** 檔案雜湊值 */
  checksum?: string;
  /** 自訂 metadata */
  metadata?: {[key: string]: unknown | null};
};
} | {
  /** 唯一的工作流程追蹤 ID，用於關聯整個檔案上傳流程中的各個階段 */
  notifyUploadId: string;
  /** 批次建立檔案的輸入資料，陣列中的每一筆皆會建立一個檔案 */
  files: ({
  /** 檔名 */
  name: string;
  /**
   * 檔案大小 (bytes)
   * @pattern ^d+$
   */
  size: string;
  /** 檔案雜湊值 */
  checksum?: string;
  /** 自訂 metadata */
  metadata?: {[key: string]: unknown | null};
})[];
};

export type PostApiV1FileTusIntent201 = {
  success: boolean;
  traceId: string;
};

export type PostApiV1FileTusSealBody = {
  fileId: string;
  checksum: string;
  fileName: string;
};

export type PostApiV1FileTusSeal200 = {
  success: boolean;
  traceId: string;
};

/**
 * 新增檔案分類資料
 */
export type PostApiV1FileCategoryCreateBody = {
  /**
   * 分類代碼，例如 IMAGE、VIDEO、DOC
   * @minLength 1
   */
  code: string;
  /**
   * 分類名稱
   * @minLength 1
   */
  name: string;
  /** 分類描述 */
  description?: string;
};

/**
 * 新增檔案分類結果
 */
export type PostApiV1FileCategoryCreate201 = {
  id: number;
  code: string;
  name: string;
  description: string | null;
};

/**
 * 新增副檔名資料
 */
export type PostApiV1FileExtensionCreateBody = {
  /**
   * 副檔名代碼，例如 jpg、png、pdf
   * @minLength 1
   */
  code: string;
  /** MIME 類型 */
  mimeType?: string;
  /** 副檔名顯示名稱 */
  name?: string;
  /** 描述說明 */
  description?: string;
  /**
   * 所屬分類 ID（與 categoryCode 擇一提供）
   * @minimum 0
   * @exclusiveMinimum true
   */
  categoryId?: number;
  /**
   * 所屬分類代碼（與 categoryId 擇一提供），例如 IMAGE、VIDEO、DOC
   * @minLength 1
   */
  categoryCode?: string;
};

/**
 * 新增副檔名結果
 */
export type PostApiV1FileExtensionCreate201 = {
  id: number;
  code: string;
  mimeType: string | null;
  name: string | null;
  description: string | null;
  categoryId: number;
};

/**
 * 單一或批次建立項目的輸入資料
 */
export type PostApiV1ItemCreateBody = ({
  /**
   * 項目標題，至少 1 個字元
   * @minLength 1
   */
  title: string;
  /** 項目描述，用於補充說明此項目內容 */
  description?: string;
  /** 自訂鍵值對 metadata，可存放額外設定或標記 */
  metadata?: {[key: string]: unknown | null};
  /** 項目類型 */
  type: 'WORK' | 'SERIES' | 'COLLECTION' | 'FILE_CONTAINER';
  /** 項目狀態 */
  status: 'ONGOING' | 'COMPLETED' | 'HIATUS' | 'UPCOMING' | 'DRAFT' | 'PRIVATE' | 'ACTIVE' | 'ARCHIVED' | 'LOCKED' | 'HIDDEN' | 'PROCESSING' | 'DELETED' | 'FAILED';
  /** 發布時間 (ISO-8601) */
  publishedTime?: string;
})[] | {
  /**
   * 項目標題，至少 1 個字元
   * @minLength 1
   */
  title: string;
  /** 項目描述，用於補充說明此項目內容 */
  description?: string;
  /** 自訂鍵值對 metadata，可存放額外設定或標記 */
  metadata?: {[key: string]: unknown | null};
  /** 項目類型 */
  type: 'WORK' | 'SERIES' | 'COLLECTION' | 'FILE_CONTAINER';
  /** 項目狀態 */
  status: 'ONGOING' | 'COMPLETED' | 'HIATUS' | 'UPCOMING' | 'DRAFT' | 'PRIVATE' | 'ACTIVE' | 'ARCHIVED' | 'LOCKED' | 'HIDDEN' | 'PROCESSING' | 'DELETED' | 'FAILED';
  /** 發布時間 (ISO-8601) */
  publishedTime?: string;
};

export type PostApiV1ItemCreate201 = {
  success: boolean;
  traceId: string;
};

export type GetApiV1FilesFileIdServe404 = {
  error: string;
};

/**
 * 單筆或批次建立使用者輸入
 */
export type PostApiV1UserCreateBody = ({
  /**
   * 使用者名稱，至少 1 個字元
   * @minLength 1
   */
  name: string;
  /** 自訂鍵值對 redundancy，可存放額外資訊 */
  redundancy?: {[key: string]: unknown | null};
  /** 使用者狀態，未提供時由資料庫使用預設值 */
  status?: 'PENDING' | 'ACTIVE' | 'LOCKED' | 'SUSPENDED' | 'DELETED';
})[] | {
  /**
   * 使用者名稱，至少 1 個字元
   * @minLength 1
   */
  name: string;
  /** 自訂鍵值對 redundancy，可存放額外資訊 */
  redundancy?: {[key: string]: unknown | null};
  /** 使用者狀態，未提供時由資料庫使用預設值 */
  status?: 'PENDING' | 'ACTIVE' | 'LOCKED' | 'SUSPENDED' | 'DELETED';
};

export type PostApiV1UserCreate201 = {
  success: boolean;
  traceId: string;
};

