services:
  workspace:
    image: mcr.microsoft.com/devcontainers/javascript-node:22
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    ports:
      - "4200:4200"
      - "3000:3000"