/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  PostApiV1ArchiveConcept202,
  PostApiV1ArchiveConceptBodyItem,
  PostApiV1ArchiveDelete202,
  PostApiV1ArchiveDeleteBodyItem,
  PostApiV1ArchiveIntent200,
  PostApiV1ArchiveIntentBody,
  PostApiV1ArchiveStructure200Item,
  PostApiV1ArchiveStructureBody,
  PostApiV1OntologyDelete202,
  PostApiV1OntologyDeleteBody,
  PostApiV1OntologyEditor202,
  PostApiV1OntologyEditorBody,
  PostApiV1OntologyRegistry202,
  PostApiV1OntologyRegistryBody,
  PostApiV1OntologyResolver202,
  PostApiV1OntologyResolverBody
} from '../model';

import { angularHttp } from '.././angular-http';








@Injectable({ providedIn: 'root' })
export class DefaultService {
  private readonly http = inject(HttpClient);
/**
 * @summary SSE 事件
 */
 getApiV1Stream<TData = string>(

 ) {
      return angularHttp<TData>(
      {url: `/api/v1/stream`, method: 'GET'
    },
      this.http,
      );
    }
   postApiV1ArchiveConcept<TData = PostApiV1ArchiveConcept202>(
    postApiV1ArchiveConceptBodyItem?: PostApiV1ArchiveConceptBodyItem[],
 ) {
      return angularHttp<TData>(
      {url: `/api/v1/archive/concept`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1ArchiveConceptBodyItem
    },
      this.http,
      );
    }
   postApiV1ArchiveDelete<TData = PostApiV1ArchiveDelete202>(
    postApiV1ArchiveDeleteBodyItem?: PostApiV1ArchiveDeleteBodyItem[],
 ) {
      return angularHttp<TData>(
      {url: `/api/v1/archive/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1ArchiveDeleteBodyItem
    },
      this.http,
      );
    }
  /**
 * @summary 瀏覽 檔案 結構
 */
 postApiV1ArchiveStructure<TData = PostApiV1ArchiveStructure200Item[]>(
    postApiV1ArchiveStructureBody?: PostApiV1ArchiveStructureBody,
 ) {
      return angularHttp<TData>(
      {url: `/api/v1/archive/structure`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1ArchiveStructureBody
    },
      this.http,
      );
    }
  /**
 * 在 Tus 正式開始前先建立檔案意圖與暫存狀態。
 * @summary 建立 Tus 上傳意圖
 */
 postApiV1ArchiveIntent<TData = PostApiV1ArchiveIntent200>(
    postApiV1ArchiveIntentBody?: PostApiV1ArchiveIntentBody,
 ) {
      return angularHttp<TData>(
      {url: `/api/v1/archive/intent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1ArchiveIntentBody
    },
      this.http,
      );
    }
  /**
 * 刪除一個實體，並刪除關聯。
 * @summary 刪除實體
 */
 postApiV1OntologyDelete<TData = PostApiV1OntologyDelete202>(
    postApiV1OntologyDeleteBody?: PostApiV1OntologyDeleteBody,
 ) {
      return angularHttp<TData>(
      {url: `/api/v1/ontology/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1OntologyDeleteBody
    },
      this.http,
      );
    }
  /**
 * @summary 修改實體的資料
 */
 postApiV1OntologyEditor<TData = PostApiV1OntologyEditor202>(
    postApiV1OntologyEditorBody?: PostApiV1OntologyEditorBody,
 ) {
      return angularHttp<TData>(
      {url: `/api/v1/ontology/editor`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1OntologyEditorBody
    },
      this.http,
      );
    }
   postApiV1OntologyRegistry<TData = PostApiV1OntologyRegistry202>(
    postApiV1OntologyRegistryBody?: PostApiV1OntologyRegistryBody,
 ) {
      return angularHttp<TData>(
      {url: `/api/v1/ontology/registry`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1OntologyRegistryBody
    },
      this.http,
      );
    }
  /**
 * @summary 取得實體圖形與資訊
 */
 postApiV1OntologyResolver<TData = PostApiV1OntologyResolver202>(
    postApiV1OntologyResolverBody?: PostApiV1OntologyResolverBody,
 ) {
      return angularHttp<TData>(
      {url: `/api/v1/ontology/resolver`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV1OntologyResolverBody
    },
      this.http,
      );
    }
  /**
 * 以 fileId 從磁碟讀取原始檔案，回傳 binary content 與正確的 Content-Type。圖片類型可直接作為 <img src="..."> 使用。
 * @summary 讀取檔案原始內容
 */
 getApiV1RawFileId<TData = Blob>(
    fileId: string,
 ) {
      return angularHttp<TData>(
      {url: `/api/v1/raw/${fileId}`, method: 'GET',
        responseType: 'blob'
    },
      this.http,
      );
    }
  };

export type GetApiV1StreamClientResult = NonNullable<string>
export type PostApiV1ArchiveConceptClientResult = NonNullable<PostApiV1ArchiveConcept202>
export type PostApiV1ArchiveDeleteClientResult = NonNullable<PostApiV1ArchiveDelete202>
export type PostApiV1ArchiveStructureClientResult = NonNullable<PostApiV1ArchiveStructure200Item[]>
export type PostApiV1ArchiveIntentClientResult = NonNullable<PostApiV1ArchiveIntent200>
export type PostApiV1OntologyDeleteClientResult = NonNullable<PostApiV1OntologyDelete202>
export type PostApiV1OntologyEditorClientResult = NonNullable<PostApiV1OntologyEditor202>
export type PostApiV1OntologyRegistryClientResult = NonNullable<PostApiV1OntologyRegistry202>
export type PostApiV1OntologyResolverClientResult = NonNullable<PostApiV1OntologyResolver202>
export type GetApiV1RawFileIdClientResult = NonNullable<Blob>
