FROM mcr.microsoft.com/devcontainers/javascript-node:22

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python3.13-venv \
    && rm -rf /var/lib/apt/lists/*