/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1ArchiveIntentBodyFileListItemMetadata } from './postApiV1ArchiveIntentBodyFileListItemMetadata';

export type PostApiV1ArchiveIntentBodyFileListItem = {
  id: string;
  name: string;
  /** @minimum 0 */
  size: number;
  /** 警告，目前 @hono/zod-openapi@1.6.3 不支援 zod@4.6.5 的z.json()，需要自行覆蓋預設才能正常開啟swagger */
  metadata?: PostApiV1ArchiveIntentBodyFileListItemMetadata;
};
