/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1ArchiveConceptBodyItemMetadataListItem } from './postApiV1ArchiveConceptBodyItemMetadataListItem';

export type PostApiV1ArchiveConceptBodyItem = {
  /**
     * 目標archive
     * @minItems 1
     */
  targetIdList: string[];
  /** 動態新增概念，用於增加尚未存在的屬性 */
  metadataList?: PostApiV1ArchiveConceptBodyItemMetadataListItem[];
};
