/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1ArchiveConceptBodyItemMetadataListItemKey } from './postApiV1ArchiveConceptBodyItemMetadataListItemKey';
import type { PostApiV1ArchiveConceptBodyItemMetadataListItemValueItem } from './postApiV1ArchiveConceptBodyItemMetadataListItemValueItem';

export type PostApiV1ArchiveConceptBodyItemMetadataListItem = {
  key: PostApiV1ArchiveConceptBodyItemMetadataListItemKey;
  value: PostApiV1ArchiveConceptBodyItemMetadataListItemValueItem[];
};
