/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1OntologyResolver202EdgesItem } from './postApiV1OntologyResolver202EdgesItem';
import type { PostApiV1OntologyResolver202NodesItem } from './postApiV1OntologyResolver202NodesItem';

export type PostApiV1OntologyResolver202 = {
  nodes: PostApiV1OntologyResolver202NodesItem[];
  edges: PostApiV1OntologyResolver202EdgesItem[];
};
