/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1OntologyRegistryBodyRegistryListItem } from './postApiV1OntologyRegistryBodyRegistryListItem';

export type PostApiV1OntologyRegistryBody = {
  notifyId: string;
  registryList: PostApiV1OntologyRegistryBodyRegistryListItem[];
};
