/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV1ArchiveStructure200ItemType = typeof PostApiV1ArchiveStructure200ItemType[keyof typeof PostApiV1ArchiveStructure200ItemType];


export const PostApiV1ArchiveStructure200ItemType = {
  WORK: 'WORK',
  SERIES: 'SERIES',
  COLLECTION: 'COLLECTION',
  FILE_CONTAINER: 'FILE_CONTAINER',
} as const;
