/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV1ArchiveConceptBodyItemMetadataListItemValueItem = {
  id: string;
} | {
  /** @minLength 1 */
  name: string;
  description?: string;
  metadata?: {[key: string]: string | number | boolean | string[]};
};
