/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1OntologyResolver202NodesItemData } from './postApiV1OntologyResolver202NodesItemData';

export type PostApiV1OntologyResolver202NodesItem = {
  data: PostApiV1OntologyResolver202NodesItemData;
};
