/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 警告，目前 @hono/zod-openapi@1.6.3 不支援 zod@4.6.5 的z.json()，需要自行覆蓋預設才能正常開啟swagger
 */
export type PostApiV1ArchiveTusIntentBodyFileListItemMetadata = { [key: string]: unknown };
