/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV1OntologyResolver202NodesItemData = {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  metadata?: unknown;
  systemMetadata?: unknown;
  version: number;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  deletedAt: string | null;
  /** @nullable */
  verifiedAt: string | null;
  /** @nullable */
  verifiedBy: string | null;
  [key: string]: unknown;
};
