/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1ArchiveIntentBodyFileListItem } from './postApiV1ArchiveIntentBodyFileListItem';

export type PostApiV1ArchiveIntentBody = {
  fileList: PostApiV1ArchiveIntentBodyFileListItem[];
};
