/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1OntologyEditorBodyRegistryListItem } from './postApiV1OntologyEditorBodyRegistryListItem';

export type PostApiV1OntologyEditorBody = {
  notifyId: string;
  registryList: PostApiV1OntologyEditorBodyRegistryListItem[];
};
