/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV1ArchiveStructure200ItemStatus = typeof PostApiV1ArchiveStructure200ItemStatus[keyof typeof PostApiV1ArchiveStructure200ItemStatus];


export const PostApiV1ArchiveStructure200ItemStatus = {
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  HIATUS: 'HIATUS',
  UPCOMING: 'UPCOMING',
  DRAFT: 'DRAFT',
  PRIVATE: 'PRIVATE',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
  LOCKED: 'LOCKED',
  HIDDEN: 'HIDDEN',
  PROCESSING: 'PROCESSING',
  DELETED: 'DELETED',
  FAILED: 'FAILED',
} as const;
