/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1OntologyResolver200NodesItemData } from './postApiV1OntologyResolver200NodesItemData';

export type PostApiV1OntologyResolver200NodesItem = {
  data: PostApiV1OntologyResolver200NodesItemData;
};
