/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV1ArchiveTusSealBody = {
  notifyId: string;
  fileId: string;
  workflowId: string;
};
