/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1ArchiveTusIntentBodyFileListItem } from './postApiV1ArchiveTusIntentBodyFileListItem';

export type PostApiV1ArchiveTusIntentBody = {
  fileList: PostApiV1ArchiveTusIntentBodyFileListItem[];
};
