/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1OntologyResolver200EdgesItemData } from './postApiV1OntologyResolver200EdgesItemData';

export type PostApiV1OntologyResolver200EdgesItem = {
  data: PostApiV1OntologyResolver200EdgesItemData;
};
