/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1OntologyResolver202EdgesItemData } from './postApiV1OntologyResolver202EdgesItemData';

export type PostApiV1OntologyResolver202EdgesItem = {
  data: PostApiV1OntologyResolver202EdgesItemData;
};
