/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV1OntologyResolverBody = {
  showDeleted?: boolean;
  operate: 'CHILDREN';
  parentId: string;
} | {
  showDeleted?: boolean;
  operate: 'ROOT';
} | {
  showDeleted?: boolean;
  operate: 'ALL';
};
