/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV1OntologyResolver202EdgesItemData = {
  id: string;
  source: string;
  target: string;
  /** @nullable */
  label?: string | null;
};
