/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1OntologyEditorBodyRegistryListItemRegistry } from './postApiV1OntologyEditorBodyRegistryListItemRegistry';

export type PostApiV1OntologyEditorBodyRegistryListItem = {
  id: string;
  registry: PostApiV1OntologyEditorBodyRegistryListItemRegistry;
};
