/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV1ArchiveStructureBody = {
  /** 父節點 ID，省略則為頂層 */
  parentId?: string;
  /** 是否顯示已刪除項目 */
  showDeleted?: boolean;
};
