/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1OntologyEditorBodyRegistryListItemRegistryMetadata } from './postApiV1OntologyEditorBodyRegistryListItemRegistryMetadata';

export type PostApiV1OntologyEditorBodyRegistryListItemRegistry = {
  /** @minLength 1 */
  name: string;
  description?: string;
  metadata?: PostApiV1OntologyEditorBodyRegistryListItemRegistryMetadata;
};
