/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1OntologyResolver200EdgesItem } from './postApiV1OntologyResolver200EdgesItem';
import type { PostApiV1OntologyResolver200NodesItem } from './postApiV1OntologyResolver200NodesItem';

export type PostApiV1OntologyResolver200 = {
  nodes: PostApiV1OntologyResolver200NodesItem[];
  edges: PostApiV1OntologyResolver200EdgesItem[];
};
