/**
 * Generated by orval 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1OntologyRegistryBodyRegistryListItemMetadata } from './postApiV1OntologyRegistryBodyRegistryListItemMetadata';

export type PostApiV1OntologyRegistryBodyRegistryListItem = {
  /** @minLength 1 */
  name: string;
  description?: string;
  metadata?: PostApiV1OntologyRegistryBodyRegistryListItemMetadata;
};
